-- V4__cleanup_duplicate_notifications.sql
-- Clean up duplicate order notifications generated by scheduler loop

WITH CTE AS (
    SELECT notif_id,
           ROW_NUMBER() OVER (
               PARTITION BY username, order_id, type 
               ORDER BY created_at DESC, notif_id DESC
           ) AS row_num
    FROM Order_Notifications
    WHERE order_id IS NOT NULL
)
DELETE FROM Order_Notifications
WHERE notif_id IN (
    SELECT notif_id FROM CTE WHERE row_num > 1
);
